# Generated by Django 5.0.1 on 2024-01-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('image', models.ImageField(upload_to='images/shoes_categories', verbose_name='تصویر دسته بندی')),
                ('image_two', models.ImageField(upload_to='images/shoes_categories', verbose_name='تصویر دوم دسته بندی')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیر فعال')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی کفش',
                'verbose_name_plural': 'دسته بندی های کفش',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='عنوان در url')),
                ('image', models.ImageField(upload_to='images/shoes', verbose_name='تصویر محصول')),
                ('price', models.CharField(max_length=100, verbose_name='قیمت')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیر فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه محصول')),
                ('description', models.TextField(verbose_name='توضیحات اصلی')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productbrand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.shoescategory', verbose_name='برای دسته بندی')),
            ],
            options={
                'verbose_name': 'کفش',
                'verbose_name_plural': 'کفش ها',
            },
        ),
    ]
