# Generated by Django 5.0.1 on 2024-01-19 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_shoescategory_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoescategory',
            name='gender',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='product_module.person', verbose_name='جنسیت'),
            preserve_default=False,
        ),
    ]
