# Generated by Django 5.0.1 on 2024-01-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_productcomment_shoes_alter_productcomment_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'نظر محصول', 'verbose_name_plural': 'نظرات محصول'},
        ),
    ]
