# Generated by Django 5.0.1 on 2024-01-28 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_shoes_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='product_favorites', to=settings.AUTH_USER_MODEL, verbose_name='علاقه مندی ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='shoes_favorites', to=settings.AUTH_USER_MODEL, verbose_name='علاقه مندی ها'),
        ),
    ]
