# Generated by Django 5.0.1 on 2024-01-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس بنر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('position', models.CharField(choices=[('home_page', 'صفحه اصلی'), ('product_list', 'لیست محصولات'), ('product_detail', 'جزییات محصولات'), ('blog', 'وبلاگ'), ('product_catalog', 'کاتالوگ محصولات'), ('shoes', 'کفش ها')], max_length=200, verbose_name='جایگاه بنر')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
