# Generated by Django 5.0.1 on 2024-01-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='image',
            field=models.ImageField(default=False, upload_to='images/site_banners', verbose_name='تصویر بنر'),
            preserve_default=False,
        ),
    ]
