# Generated by Django 5.0.1 on 2024-01-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_sitesliders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesliders',
            name='sub_title',
        ),
    ]
