# Generated by Django 5.0.1 on 2024-01-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_remove_sitesliders_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesliders',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس اسلایدر'),
        ),
    ]
