# Generated by Django 5.0.1 on 2024-01-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_sitesliders_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('home_page_up', 'صفحه اصلی_قسمت بالایی'), ('home_page_down', 'صفحه اصلی_قسمت پایینی'), ('product_list', 'لیست محصولات'), ('product_detail', 'جزییات محصولات'), ('blog', 'وبلاگ'), ('product_catalog', 'کاتالوگ محصولات'), ('shoes', 'کفش ها')], max_length=200, verbose_name='جایگاه بنر'),
        ),
    ]
