# Generated by Django 5.0.1 on 2024-01-21 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان مقاله')),
                ('image', models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, verbose_name='عنوان در url')),
                ('short_description', models.TextField(verbose_name='توضیحات نقل قول')),
                ('blockquote', models.TextField(verbose_name='نقل قول')),
                ('paragraph', models.TextField(verbose_name='سطر های مقاله')),
                ('author', models.ForeignKey(auto_created=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
