# Generated by Django 5.0.1 on 2024-01-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_remove_articlegallery_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlegallery',
            name='image_2',
            field=models.ImageField(default=False, upload_to='images/articles/article_gallery', verbose_name='تصویر دوم مقاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlegallery',
            name='image_3',
            field=models.ImageField(default=False, upload_to='images/articles/article_gallery', verbose_name='تصویر سوم مقاله'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='image',
            field=models.ImageField(upload_to='images/articles/article_gallery', verbose_name='تصویر اول مقاله'),
        ),
    ]
