# Generated by Django 5.0.1 on 2024-01-26 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_remove_articlegallery_image_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان مقاله')),
                ('image', models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, verbose_name='عنوان در url')),
                ('blockquote', models.TextField(verbose_name='نقل قول')),
                ('short_description', models.TextField(verbose_name='توضیحات نقل قول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله بالایی',
                'verbose_name_plural': 'مقالات بالایی',
            },
        ),
    ]
